apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: reyada-homecare
  labels:
    app: kibana
    healthcare-platform: "true"
    doh-compliant: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        healthcare-platform: "true"
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.8.0
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "https://elasticsearch-client:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: password
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "none"
        - name: SERVER_NAME
          value: "reyada-kibana"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: XPACK_MONITORING_ENABLED
          value: "true"
        - name: LOGGING_QUIET
          value: "false"
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        - name: kibana-dashboards
          mountPath: /usr/share/kibana/config/dashboards
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
      - name: kibana-dashboards
        configMap:
          name: kibana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: reyada-homecare
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: reyada-homecare
data:
  kibana.yml: |
    server.name: "reyada-kibana"
    server.host: "0.0.0.0"
    server.port: 5601
    
    elasticsearch.hosts: ["https://elasticsearch-client:9200"]
    elasticsearch.username: "elastic"
    elasticsearch.ssl.verificationMode: none
    
    # Healthcare-specific configurations
    server.defaultRoute: "/app/dashboards#/view/healthcare-overview"
    
    # Security settings for DOH compliance
    xpack.security.enabled: true
    xpack.security.session.idleTimeout: "1h"
    xpack.security.session.lifespan: "8h"
    
    # Audit logging
    xpack.security.audit.enabled: true
    
    # Monitoring
    xpack.monitoring.enabled: true
    xpack.monitoring.kibana.collection.enabled: true
    
    # Healthcare-specific index patterns
    kibana.defaultAppId: "dashboards"
    
    # Data views for healthcare logs
    data.search.timeout: 60000
    
    # Custom branding for healthcare platform
    server.customResponseHeaders:
      X-Healthcare-Platform: "Reyada"
      X-DOH-Compliance: "Enabled"
    
    # Logging configuration
    logging.appenders:
      file:
        type: file
        fileName: /usr/share/kibana/logs/kibana.log
        layout:
          type: json
    logging.loggers:
      - name: http.server.response
        level: debug
        appenders: [file]
      - name: elasticsearch.query
        level: debug
        appenders: [file]
    
    # Performance settings
    elasticsearch.requestTimeout: 60000
    elasticsearch.shardTimeout: 30000
    
    # Healthcare data retention awareness
    savedObjects.maxImportPayloadBytes: 26214400
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-dashboards
  namespace: reyada-homecare
data:
  healthcare-overview.json: |
    {
      "version": "8.8.0",
      "objects": [
        {
          "id": "healthcare-overview",
          "type": "dashboard",
          "attributes": {
            "title": "Healthcare Platform Overview",
            "description": "DOH-compliant healthcare platform monitoring dashboard",
            "panelsJSON": "[{\"version\":\"8.8.0\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"1\"},\"panelIndex\":\"1\",\"embeddableConfig\":{},\"panelRefName\":\"panel_1\"}]",
            "timeRestore": false,
            "timeTo": "now",
            "timeFrom": "now-24h",
            "refreshInterval": {
              "pause": false,
              "value": 30000
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            }
          },
          "references": [
            {
              "name": "panel_1",
              "type": "visualization",
              "id": "patient-activity-logs"
            }
          ]
        },
        {
          "id": "patient-activity-logs",
          "type": "visualization",
          "attributes": {
            "title": "Patient Activity Logs",
            "description": "Real-time patient activity monitoring for DOH compliance",
            "visState": "{\"title\":\"Patient Activity Logs\",\"type\":\"histogram\",\"params\":{\"grid\":{\"categoryLines\":false,\"style\":{\"color\":\"#eee\"}},\"categoryAxes\":[{\"id\":\"CategoryAxis-1\",\"type\":\"category\",\"position\":\"bottom\",\"show\":true,\"style\":{},\"scale\":{\"type\":\"linear\"},\"labels\":{\"show\":true,\"truncate\":100},\"title\":{}}],\"valueAxes\":[{\"id\":\"ValueAxis-1\",\"name\":\"LeftAxis-1\",\"type\":\"value\",\"position\":\"left\",\"show\":true,\"style\":{},\"scale\":{\"type\":\"linear\",\"mode\":\"normal\"},\"labels\":{\"show\":true,\"rotate\":0,\"filter\":false,\"truncate\":100},\"title\":{\"text\":\"Count\"}}],\"seriesParams\":[{\"show\":\"true\",\"type\":\"histogram\",\"mode\":\"stacked\",\"data\":{\"label\":\"Count\",\"id\":\"1\"},\"valueAxis\":\"ValueAxis-1\",\"drawLinesBetweenPoints\":true,\"showCircles\":true}],\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"times\":[],\"addTimeMarker\":false},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"date_histogram\",\"schema\":\"segment\",\"params\":{\"field\":\"@timestamp\",\"interval\":\"auto\",\"customInterval\":\"2h\",\"min_doc_count\":1,\"extended_bounds\":{}}}]}",
            "uiStateJSON": "{}",
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-*\",\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        }
      ]
    }
  compliance-dashboard.json: |
    {
      "version": "8.8.0",
      "objects": [
        {
          "id": "doh-compliance-dashboard",
          "type": "dashboard",
          "attributes": {
            "title": "DOH Compliance Dashboard",
            "description": "Monitor DOH compliance metrics and audit trails",
            "panelsJSON": "[{\"version\":\"8.8.0\",\"gridData\":{\"x\":0,\"y\":0,\"w\":12,\"h\":15,\"i\":\"1\"},\"panelIndex\":\"1\",\"embeddableConfig\":{},\"panelRefName\":\"panel_1\"},{\"version\":\"8.8.0\",\"gridData\":{\"x\":12,\"y\":0,\"w\":12,\"h\":15,\"i\":\"2\"},\"panelIndex\":\"2\",\"embeddableConfig\":{},\"panelRefName\":\"panel_2\"}]",
            "timeRestore": false,
            "timeTo": "now",
            "timeFrom": "now-7d",
            "refreshInterval": {
              "pause": false,
              "value": 60000
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
            }
          },
          "references": [
            {
              "name": "panel_1",
              "type": "visualization",
              "id": "compliance-violations"
            },
            {
              "name": "panel_2",
              "type": "visualization",
              "id": "audit-trail"
            }
          ]
        },
        {
          "id": "compliance-violations",
          "type": "visualization",
          "attributes": {
            "title": "Compliance Violations",
            "description": "Track DOH compliance violations and security incidents",
            "visState": "{\"title\":\"Compliance Violations\",\"type\":\"pie\",\"params\":{\"addTooltip\":true,\"addLegend\":true,\"legendPosition\":\"right\",\"isDonut\":true},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"compliance_flag\",\"size\":10,\"order\":\"desc\",\"orderBy\":\"1\"}}]}",
            "uiStateJSON": "{}",
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-*\",\"query\":{\"bool\":{\"must\":[{\"exists\":{\"field\":\"compliance_flag\"}}]}},\"filter\":[]}"
            }
          }
        },
        {
          "id": "audit-trail",
          "type": "visualization",
          "attributes": {
            "title": "Audit Trail",
            "description": "Healthcare platform audit trail for DOH compliance",
            "visState": "{\"title\":\"Audit Trail\",\"type\":\"table\",\"params\":{\"perPage\":10,\"showPartialRows\":false,\"showMeticsAtAllLevels\":false,\"sort\":{\"columnIndex\":null,\"direction\":null},\"showTotal\":false,\"totalFunc\":\"sum\"},\"aggs\":[{\"id\":\"1\",\"enabled\":true,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":\"2\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"bucket\",\"params\":{\"field\":\"user_id\",\"size\":20,\"order\":\"desc\",\"orderBy\":\"1\"}},{\"id\":\"3\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"bucket\",\"params\":{\"field\":\"action\",\"size\":10,\"order\":\"desc\",\"orderBy\":\"1\"}},{\"id\":\"4\",\"enabled\":true,\"type\":\"terms\",\"schema\":\"bucket\",\"params\":{\"field\":\"resource\",\"size\":10,\"order\":\"desc\",\"orderBy\":\"1\"}}]}",
            "uiStateJSON": "{}",
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"index\":\"healthcare-*\",\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        }
      ]
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-setup
  namespace: reyada-homecare
spec:
  template:
    spec:
      containers:
      - name: setup
        image: curlimages/curl:8.1.0
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Kibana to be ready
          until curl -f http://kibana:5601/api/status; do
            echo "Waiting for Kibana..."
            sleep 10
          done
          
          # Create healthcare index pattern
          curl -X POST "http://kibana:5601/api/saved_objects/index-pattern/healthcare-*" \
            -H "Content-Type: application/json" \
            -H "kbn-xsrf: true" \
            -d '{
              "attributes": {
                "title": "healthcare-*",
                "timeFieldName": "@timestamp",
                "fields": "[{\"name\":\"@timestamp\",\"type\":\"date\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"patient_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"user_id\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"action\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true},{\"name\":\"compliance_flag\",\"type\":\"string\",\"searchable\":true,\"aggregatable\":true}]"
              }
            }'
          
          # Import healthcare dashboards
          curl -X POST "http://kibana:5601/api/saved_objects/_import" \
            -H "kbn-xsrf: true" \
            -F "file=@/usr/share/kibana/config/dashboards/healthcare-overview.json"
          
          curl -X POST "http://kibana:5601/api/saved_objects/_import" \
            -H "kbn-xsrf: true" \
            -F "file=@/usr/share/kibana/config/dashboards/compliance-dashboard.json"
          
          echo "Kibana setup completed"
      restartPolicy: OnFailure