apiVersion: apps/v1
kind: Deployment
metadata:
  name: reyada-api-gateway
  namespace: reyada-homecare
  labels:
    app: reyada-api-gateway
spec:
  replicas: 8
  selector:
    matchLabels:
      app: reyada-api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: reyada-api-gateway
    spec:
      containers:
      - name: reyada-api-gateway
        image: ${ECR_REPOSITORY_URI}/reyada-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8000"
        - name: AUTH_SERVICE_URL
          value: "http://reyada-auth-service:8001"
        - name: PATIENT_SERVICE_URL
          value: "http://reyada-patient-service:8002"
        - name: CLINICAL_SERVICE_URL
          value: "http://reyada-clinical-service:8003"
        - name: COMPLIANCE_SERVICE_URL
          value: "http://reyada-compliance-service:8004"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: reyada-secrets
              key: jwt_secret
        - name: RATE_LIMIT_WINDOW_MS
          value: "900000"
        - name: RATE_LIMIT_MAX
          value: "500"
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: reyada-api-gateway
  namespace: reyada-homecare
spec:
  selector:
    app: reyada-api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reyada-api-gateway-ingress
  namespace: reyada-homecare
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: ${ACM_CERTIFICATE_ARN}
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/success-codes: "200-399"
    alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=60"
    external-dns.alpha.kubernetes.io/hostname: "api.reyada-homecare.ae"
    external-dns.alpha.kubernetes.io/ttl: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  rules:
  - host: api.reyada-homecare.ae
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reyada-api-gateway
            port:
              number: 8000
  tls:
  - hosts:
    - api.reyada-homecare.ae
    secretName: reyada-api-tls-secret
