# Enhanced Auto-scaling Configuration for Reyada Homecare Platform
# Optimized for healthcare workloads with DOH compliance requirements
# Includes predictive scaling and healthcare-specific metrics

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-frontend-hpa
  namespace: reyada-homecare
  labels:
    app: reyada-frontend
    component: autoscaling
    healthcare-tier: critical
    compliance: doh-uae
    version: enhanced
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","reason":"ReadyForNewScale"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":45}}]'
    healthcare.reyada.com/scaling-profile: "clinical-workload"
    healthcare.reyada.com/peak-hours: "08:00-18:00"
    healthcare.reyada.com/emergency-scaling: "enabled"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-frontend  # Dynamic target updated by deployment scripts
  minReplicas: 3  # Minimum for high availability
  maxReplicas: 20  # Increased for healthcare peak loads and emergency scaling
  metrics:
  # CPU utilization - conservative for healthcare responsiveness
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Lower threshold for healthcare responsiveness
  # Memory utilization - conservative to prevent OOM
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70  # Conservative memory threshold
  # Healthcare-specific custom metrics
  - type: Pods
    pods:
      metric:
        name: patient_requests_per_second
      target:
        type: AverageValue
        averageValue: "8"  # Scale when patient requests exceed 8/sec per pod
  - type: Pods
    pods:
      metric:
        name: clinical_assessment_processing_time
      target:
        type: AverageValue
        averageValue: "2000"  # Scale when processing time exceeds 2 seconds
  - type: Object
    object:
      metric:
        name: clinical_assessment_queue_length
      describedObject:
        apiVersion: v1
        kind: Service
        name: reyada-frontend-service
      target:
        type: Value
        value: "3"  # Scale when assessment queue exceeds 3
  - type: Object
    object:
      metric:
        name: doh_compliance_processing_load
      describedObject:
        apiVersion: v1
        kind: Service
        name: reyada-frontend-service
      target:
        type: Value
        value: "5"  # Scale when DOH compliance processing load is high
  # Emergency scaling metrics
  - type: Pods
    pods:
      metric:
        name: emergency_patient_requests
      target:
        type: AverageValue
        averageValue: "1"  # Immediate scaling for emergency requests
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20  # Faster scale-up for healthcare emergencies
      policies:
      # Aggressive scaling for emergency situations
      - type: Percent
        value: 200  # Double capacity quickly if needed
        periodSeconds: 20
      # Moderate scaling for normal load increases
      - type: Percent
        value: 50
        periodSeconds: 60
      # Pod-based scaling for fine-grained control
      - type: Pods
        value: 3  # Add 3 pods at once for healthcare workloads
        periodSeconds: 30
      selectPolicy: Max  # Use the policy that allows the highest scaling
    scaleDown:
      stabilizationWindowSeconds: 600  # Conservative scale-down (10 minutes)
      policies:
      # Very conservative scale-down to maintain healthcare service availability
      - type: Percent
        value: 5  # Only reduce by 5% at a time
        periodSeconds: 120
      - type: Pods
        value: 1  # Remove only 1 pod at a time
        periodSeconds: 180
      selectPolicy: Min  # Use the policy that allows the lowest scaling
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-api-gateway-hpa
  namespace: reyada-homecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-api-gateway
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-auth-service-hpa
  namespace: reyada-homecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-auth-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-patient-service-hpa
  namespace: reyada-homecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-patient-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-clinical-service-hpa
  namespace: reyada-homecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-clinical-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reyada-compliance-service-hpa
  namespace: reyada-homecare
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reyada-compliance-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
